### ISSUE TITLE
这个坑占了一年多了，什么时候填上呢？

### ISSUE THREAD

**Issue by ranshaw** [youngwind/blog#110]
# 不要在我的博客开 issue!
# 不要在我的博客开 issue!
# 不要在我的博客开 issue!

**Comment by youngwind** [comment]
你没看到我的提示吗？我不希望别人在我的博客上 issue ！ @ranshaw

**Comment by angellaugh** [comment]
对不起，你说的是不要fork么？我记得我取消了已经 实在抱歉
如果还有什么需要我修正的，请给个提示，我用github很少，没发现哪里有问题








Have a nice day!


在2017年09月13日 14:52，梁少峰<notifications@github.com> 写道：

你没看到我的提示吗？我不希望别人在我的博客上 issue ！ @ranshaw

**Comment by youngwind** [comment]
1. 我说的不是 fork，我说的是开 issue，这是 2 个概念。是否 fork，没有太大的关系。
2. 每开一个 issue，所有 watch 此仓库的人都会收到通知。所以，如果随意开 issue，会干扰到别人。
3. issue 作为我写博客的地方，我不希望其他人开 issue，我已经设置了 new issue 的提醒，当你想开 issue 的时候应当看到，如下图所示。
![image](https://user-images.githubusercontent.com/8401872/30370078-0c3e56de-98a9-11e7-95da-79e5079abbf0.png)
4. 熟练掌握 github 的使用还是挺有必要的。

@angellaugh @ranshaw

**Comment by angellaugh** [comment]
那我需要做什么取消的动作吗？
再次表示歉意  后面我会注意的  对不起啦






Have a nice day!


在2017年09月13日 17:31，梁少峰<notifications@github.com> 写道：
我说的不是 fork，我说的是开 issue，这是 2 个概念。是否 fork，没有太大的关系。
每开一个 issue，所有 watch 此仓库的人都会收到通知。所以，如果随意开 issue，会干扰到别人。
issue 作为我写博客的地方，我不希望其他人开 issue，我已经设置了 new issue 的提醒，当你想开 issue 的时候应当看到，如下图所示。

熟练掌握 github 的使用还是挺有必要的。

@angellaugh@ranshaw

**Comment by bitqiang** [comment]
或许可以加上一句     禁止点右下脚绿色的Submit new issue！！！

**Comment by youngwind** [comment]
嗯，无法取消，以后注意就行。 @ranshaw
