### ISSUE TITLE
安卓微信返回上一页怎么阻止刷新？

### ISSUE THREAD

**Issue by 18816793332** [youngwind/blog#111]
问题：安卓微信内置浏览器在返回上一页面，且上一页面包含AJAX代码时，页面就会被强制刷新，ios微信内置浏览器不存在该问题。请问怎么解决？（非单页应用）

**Comment by youngwind** [comment]
1. 你新建 issue 之前，没看到我的提示吗？请不要在我的博客里面新建 issue，原因请参考这里。 #110  如有技术交流问题，欢迎通过邮件的方式与我联系。
2. 关于你的问题，google 一下答案一大堆，下回提问之前，请先自行寻找方案并尝试。
![2017-11-28 9 15 38](https://user-images.githubusercontent.com/8401872/33297661-4260a7f8-d41d-11e7-83d1-88c04d51c569.png)
