### ISSUE TITLE
腾讯社招内推（已失效）

### ISSUE THREAD

**Issue by youngwind** [youngwind/blog#116]
# 岗位范围
[腾讯社招官网](https://hr.tencent.com/)上有的岗位，都能推，**不论城市，不论部门，不论种类**。

# 内推优势
简历投递一般有 4 种方式：内部推荐、猎头推荐、官网投递、第三方招聘网站投递，这些投递方式，在面试流程和面试难度上没有任何区别。然而 **HR 对内推的关注度更高，反馈也会更快**。当然，要是你最后成功入职，我还能拿伯乐奖。

# 为什么要面试
在工作以后，我渐渐明白一个道理，没有什么是永远不变的，包括你所在的公司，你所在的岗位，你所做的事情。即便你没有跳槽的想法，也应该每年（或者每两年）尝试出去面试，理由如下：

1. **居安思危**：正所谓，生于忧患，死于安乐。在一个岗位呆久了，业务和技术渐渐熟悉，很容易陷入舒适区，以为自己什么都懂了。如果不主动求变，很容易温水煮青蛙，渐渐失去竞争力。这时候，面试可以带给你压力，让你重新思考：“**我的核心竞争力是什么？我现在做的东西有意义吗？未来的发展前景如何？如果公司倒闭，部门解散，我出去还能找到同样薪资和待遇的工作吗**？”……每个人的回答都不一样，但是思考结果的方向无非两类：第一，这工作不再适合我了，我要跳槽。第二，在现在工作的基础上，其实我还可以做得更多，做得更好。这重新激发了我的斗志，我会花更多的时间去思考，去实践，争取取得突破，更上一层楼。这无论对公司和还是个人都有很大的好处。
2. **市场趋势**：低头做事的间隙，也别忘了偶尔抬头看路。选择了很差的方向，付出的努力往往很难获得应有的回报。社会发展日新月异，通过面试，跟不同公司、行业的人接触、交谈，我们能接收到一手的资讯：目前市场上对人才的要求是什么？行业的发展趋势如何？有哪些新兴的行业值得加入？有哪些传统行业正在老树发新枝？天下大势，顺之则昌，逆之则亡。**即便我们无法创造大势，也很难选中所谓最好的方向，但好歹不要选最差的那些**。
3. **模拟练习**：真正的高考前，会经历无数的模拟考，面试也一样。不是每一次面试都会拿到最终的 offer，但是每一次都会锻炼你的自信，提升你的技巧，让你下一次真正想跳槽的时候，有能力把握住机会，不会因为惊慌失措，准备不足而遗憾错过。

# 投递方式
**心动不如行动，多一次尝试，多一份收获**。
简历请发送至我的邮箱：youngwind@foxmail.com

# 注意点
1.  请先在官网上找到你想要的岗位，然后把 URL 一并发我，一次最多同时内推 3 个岗位；
2. 如果目前你已经在面试腾讯，那么内推无效，请等面试流程结束后，再把简历发我；
3. 不适用于校招与实习生。

**Comment by dwqs** [comment]
>即便你没有跳槽的想法，也应该每年（或者每两年）尝试出去面试

很赞同这点，我一般每年的金3银4、金9银10 都会出去面试面试 :grinning: :grinning:

**Comment by lkdghzh** [comment]
so,珍惜每一次面试机会，好好准备

**Comment by shadeofgod** [comment]
腾讯在深圳有没有什么用做 webapp 团队，最好是 react/ts/rxjs 这类技术栈的？

**Comment by waihoyu** [comment]
awesome！！

**Comment by xtx1130** [comment]
如果出去面了，估计肯定就跑路了。最近百度优秀的前端走了不少，心疼一下我度。。。

**Comment by lvleihere** [comment]
心疼我度
